In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
# Define a small corpus of documents
documents = [
    "the sky is blue",
    "the sun is bright",
    "the sun in the sky is bright",
    "we can see the shining sun, the bright sun"
]


In [3]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

In [4]:
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

In [5]:
tfidf_matrix.shape

(4, 5)

In [6]:
cosine_similarities = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)

In [7]:
cosine_similarities

array([[1.        , 0.        , 0.40728206, 0.        ]])

In [8]:
tfidf_matrix.toarray()

array([[0.78528828, 0.        , 0.        , 0.6191303 , 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.70710678],
       [0.        , 0.53256952, 0.        , 0.65782931, 0.53256952],
       [0.        , 0.36626037, 0.57381765, 0.        , 0.73252075]])

In [9]:
tfidf_vectorizer.get_feature_names_out()

array(['blue', 'bright', 'shining', 'sky', 'sun'], dtype=object)

In [10]:
new_sentence = ["the sky is shining"]

In [11]:
new_sentence_tfidf = tfidf_vectorizer.transform(new_sentence)

In [12]:
cosine_similarities = cosine_similarity(new_sentence_tfidf, tfidf_matrix)

In [13]:
cosine_similarities

array([[0.38332232, 0.        , 0.40728206, 0.45061227]])